import { forumContents } from './forumContent';
export type DiscussionThread = {
    courseId: string;
    classId: string;
    lecturerId: string;
    lecturerName: string;
    forumTitle: string;
    studentName: string;
    studentArgument: string;
    lecturerResponse: string;
    timestampStudent: string;
    timestampLecturer: string;
};

export const discussionThreads: DiscussionThread[] = [
    {
        ...forumContents.find((f) => f.courseId === 'SCI-4321')!,
        classId: 'SCI-4321',
        studentName: 'Alya Nurhaliza',
        studentArgument: 'I think local factories still dump chemical waste into rivers because the cost of proper disposal is too high.',
        lecturerResponse:
            'Alya, that’s a valid observation. Economic barriers are a major reason. In our next session, we’ll review cost-effective sustainable waste treatment alternatives being piloted in Southeast Asia.',
        timestampStudent: '2025-06-28T09:14:00Z',
        timestampLecturer: '2025-06-28T11:23:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-2201')!,
        classId: 'BIO-2201',
        studentName: 'Bima Prasetyo',
        studentArgument: 'Can you explain why the Calvin cycle is light-independent even though it still indirectly depends on light?',
        lecturerResponse:
            'Great question, Bima. It’s light-independent because it doesn’t require photons directly, but it uses ATP and NADPH from the light-dependent reactions.',
        timestampStudent: '2025-06-26T08:49:00Z',
        timestampLecturer: '2025-06-26T09:15:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-3010')!,
        classId: 'GEO-3010',
        studentName: 'Dewi Anggraini',
        studentArgument: 'How accurate are computer simulations in predicting future greenhouse gas effects?',
        lecturerResponse:
            'Dewi, climate models have limitations, but they’re based on decades of reliable data and constantly improved. They are essential tools for policy decisions globally.',
        timestampStudent: '2025-06-24T10:00:00Z',
        timestampLecturer: '2025-06-24T12:08:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1103')!,
        classId: 'CHEM-1103',
        studentName: 'Rafi Ilham',
        studentArgument: 'Why does electronegativity decrease down a group but increase across a period?',
        lecturerResponse:
            'Nice reasoning, Rafi. It’s due to increasing atomic radius and shielding down the group, and higher nuclear charge across a period.',
        timestampStudent: '2025-06-27T15:23:00Z',
        timestampLecturer: '2025-06-27T16:05:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-3302')!,
        classId: 'BIO-3302',
        studentName: 'Tasya Ramadhani',
        studentArgument: 'In meiosis, why is genetic variation more significant than in mitosis?',
        lecturerResponse:
            'Excellent insight, Tasya. Crossing over and independent assortment in meiosis introduce variation, unlike mitosis which produces identical cells.',
        timestampStudent: '2025-06-25T14:40:00Z',
        timestampLecturer: '2025-06-25T15:20:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-2502')!,
        classId: 'PHY-2502',
        studentName: 'Yusuf Ardiansyah',
        studentArgument: 'I get confused when resistors are in both series and parallel. How do I know which formula to use?',
        lecturerResponse: 'That’s a common concern, Yusuf. First identify nodes and loops. I’ll give you a flowchart method in class tomorrow.',
        timestampStudent: '2025-06-29T10:30:00Z',
        timestampLecturer: '2025-06-29T11:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-2222')!,
        classId: 'GEO-2222',
        studentName: 'Intan Maharani',
        studentArgument: 'Why do volcanoes mostly form near tectonic plate boundaries?',
        lecturerResponse:
            'Excellent point, Intan. It’s due to subduction and rifting processes. Check our Moodle for an animation showing the Ring of Fire.',
        timestampStudent: '2025-06-23T09:05:00Z',
        timestampLecturer: '2025-06-23T10:47:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-1205')!,
        classId: 'PHY-1205',
        studentName: 'Joko Hartono',
        studentArgument: 'Can acceleration be negative even if an object is moving forward?',
        lecturerResponse: 'Yes, Joko. That’s called deceleration. I’ll demonstrate it with a velocity-time graph during practice.',
        timestampStudent: '2025-06-26T13:11:00Z',
        timestampLecturer: '2025-06-26T14:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-5533')!,
        classId: 'SCI-5533',
        studentName: 'Citra Melani',
        studentArgument: 'Why are polar regions warming faster than the equator?',
        lecturerResponse:
            'Great question, Citra. It’s due to Arctic amplification, where loss of ice reduces reflectivity, increasing heat absorption.',
        timestampStudent: '2025-06-28T07:55:00Z',
        timestampLecturer: '2025-06-28T09:18:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1211')!,
        classId: 'CHEM-1211',
        studentName: 'Hendra Saputra',
        studentArgument: 'Can you explain how neutralization helps in treating acidic soil?',
        lecturerResponse: 'Neutralization with basic compounds like lime helps restore soil pH, improving crop yield and health.',
        timestampStudent: '2025-06-27T12:31:00Z',
        timestampLecturer: '2025-06-27T13:45:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-4120')!,
        classId: 'BIO-4120',
        studentName: 'Lisa Septiani',
        studentArgument: 'How do angiosperms adapt better than gymnosperms in tropical climates?',
        lecturerResponse:
            'Their enclosed seeds and broader leaf structures give angiosperms better reproductive and survival traits in tropical climates.',
        timestampStudent: '2025-06-25T10:27:00Z',
        timestampLecturer: '2025-06-25T11:10:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-2098')!,
        classId: 'SCI-2098',
        studentName: 'Zaki Nurman',
        studentArgument: 'Is solar energy truly sustainable if panel production emits carbon?',
        lecturerResponse:
            'Lifecycle analysis shows solar panels offset their production emissions after a few years of operation, making them net positive.',
        timestampStudent: '2025-06-24T16:00:00Z',
        timestampLecturer: '2025-06-24T16:45:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-1015')!,
        classId: 'BIO-1015',
        studentName: 'Nadia Rahma',
        studentArgument: 'Do bones store more than just calcium?',
        lecturerResponse: 'Yes, bones also store phosphorus and contain marrow that produces blood cells, playing a critical role in homeostasis.',
        timestampStudent: '2025-06-30T10:00:00Z',
        timestampLecturer: '2025-06-30T11:30:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-8787')!,
        classId: 'GEO-8787',
        studentName: 'Farhan Husein',
        studentArgument: 'Is there any way to predict earthquakes near transform faults?',
        lecturerResponse: 'There’s no exact method yet, but seismic sensors and AI-based early warnings are improving rapidly.',
        timestampStudent: '2025-06-30T14:18:00Z',
        timestampLecturer: '2025-06-30T15:05:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-2920')!,
        classId: 'CHEM-2920',
        studentName: 'Siti Marlina',
        studentArgument: 'How do electron-dot diagrams help explain bonding?',
        lecturerResponse: 'They help visualize valence electrons, making it easier to predict bonding types and molecule structures.',
        timestampStudent: '2025-06-29T08:22:00Z',
        timestampLecturer: '2025-06-29T09:01:00Z',
    },
    // Additional discussionThreads entries
    {
        ...forumContents.find((f) => f.courseId === 'PHY-2502')!,
        classId: 'PHY-2502',
        studentName: 'Rizky Handayani',
        studentArgument: 'If the net force is zero, does it always mean an object is at rest?',
        lecturerResponse: 'Not necessarily, Rizky. It could be moving at constant velocity. We’ll clarify this distinction with Newton’s first law.',
        timestampStudent: '2025-06-29T12:10:00Z',
        timestampLecturer: '2025-06-29T13:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1103')!,
        classId: 'CHEM-1103',
        studentName: 'Daniel Surya',
        studentArgument: 'Why are noble gases generally unreactive?',
        lecturerResponse: 'Good observation, Daniel. Their outermost electron shells are full, making them stable and unlikely to form bonds.',
        timestampStudent: '2025-06-27T09:00:00Z',
        timestampLecturer: '2025-06-27T10:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-2201')!,
        classId: 'BIO-2201',
        studentName: 'Salsa Fitriani',
        studentArgument: 'Do plants use ATP during photosynthesis?',
        lecturerResponse: 'Yes, Salsa. ATP is produced in the light reactions and consumed during the Calvin cycle to fix carbon.',
        timestampStudent: '2025-06-26T10:10:00Z',
        timestampLecturer: '2025-06-26T10:50:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-3010')!,
        classId: 'GEO-3010',
        studentName: 'Ilham Fauzan',
        studentArgument: 'How does deforestation impact the carbon cycle?',
        lecturerResponse: 'Ilham, trees store carbon. Cutting them down releases CO₂, accelerating climate change.',
        timestampStudent: '2025-06-24T13:15:00Z',
        timestampLecturer: '2025-06-24T14:30:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1211')!,
        classId: 'CHEM-1211',
        studentName: 'Tari Wulandari',
        studentArgument: 'Why does acid rain damage buildings?',
        lecturerResponse: 'Tari, acid rain reacts with calcium carbonate in limestone, causing erosion. We’ll explore mitigation in next class.',
        timestampStudent: '2025-06-27T14:20:00Z',
        timestampLecturer: '2025-06-27T15:10:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-1205')!,
        classId: 'PHY-1205',
        studentName: 'Fahmi Ramadhan',
        studentArgument: 'Is weight the same as mass in physics?',
        lecturerResponse: 'Not quite, Fahmi. Mass is constant, but weight is force due to gravity. We’ll solve related problems soon.',
        timestampStudent: '2025-06-26T15:50:00Z',
        timestampLecturer: '2025-06-26T16:30:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-3302')!,
        classId: 'BIO-3302',
        studentName: 'Putri Lestari',
        studentArgument: 'How does independent assortment create genetic diversity?',
        lecturerResponse: 'Great point, Putri. It randomly shuffles chromosomes into gametes, ensuring varied offspring.',
        timestampStudent: '2025-06-25T15:40:00Z',
        timestampLecturer: '2025-06-25T16:20:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-2222')!,
        classId: 'GEO-2222',
        studentName: 'Adit Santoso',
        studentArgument: 'What causes tsunamis during undersea earthquakes?',
        lecturerResponse: 'Excellent question, Adit. Vertical displacement of seabed causes massive water movement. We’ll visualize this on Friday.',
        timestampStudent: '2025-06-23T11:00:00Z',
        timestampLecturer: '2025-06-23T12:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-2098')!,
        classId: 'SCI-2098',
        studentName: 'Nisa Kamila',
        studentArgument: 'Why aren’t solar panels widely adopted despite benefits?',
        lecturerResponse: 'Adoption is growing, Nisa, but barriers include high initial costs and infrastructure limits. Incentive programs are key.',
        timestampStudent: '2025-06-24T17:15:00Z',
        timestampLecturer: '2025-06-24T18:05:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-4321')!,
        classId: 'SCI-4321',
        studentName: 'Rendra Satria',
        studentArgument: 'Are biodegradable plastics truly eco-friendly?',
        lecturerResponse: 'Interesting query, Rendra. Some are, but others require industrial composting. We’ll compare types next week.',
        timestampStudent: '2025-06-28T10:20:00Z',
        timestampLecturer: '2025-06-28T11:40:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-4321')!,
        classId: 'SCI-4321',
        studentName: 'Alya Nurhaliza',
        studentArgument: 'I think local factories still dump chemical waste into rivers because the cost of proper disposal is too high.',
        lecturerResponse:
            'Alya, that’s a valid observation. Economic barriers are a major reason. In our next session, we’ll review cost-effective sustainable waste treatment alternatives being piloted in Southeast Asia.',
        timestampStudent: '2025-06-28T09:14:00Z',
        timestampLecturer: '2025-06-28T11:23:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-2201')!,
        classId: 'BIO-2201',
        studentName: 'Bima Prasetyo',
        studentArgument: 'Can you explain why the Calvin cycle is light-independent even though it still indirectly depends on light?',
        lecturerResponse:
            'Great question, Bima. It’s light-independent because it doesn’t require photons directly, but it uses ATP and NADPH from the light-dependent reactions.',
        timestampStudent: '2025-06-26T08:49:00Z',
        timestampLecturer: '2025-06-26T09:15:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-3010')!,
        classId: 'GEO-3010',
        studentName: 'Dewi Anggraini',
        studentArgument: 'How accurate are computer simulations in predicting future greenhouse gas effects?',
        lecturerResponse:
            'Dewi, climate models have limitations, but they’re based on decades of reliable data and constantly improved. They are essential tools for policy decisions globally.',
        timestampStudent: '2025-06-24T10:00:00Z',
        timestampLecturer: '2025-06-24T12:08:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1103')!,
        classId: 'CHEM-1103',
        studentName: 'Rafi Ilham',
        studentArgument: 'Why does electronegativity decrease down a group but increase across a period?',
        lecturerResponse:
            'Nice reasoning, Rafi. It’s due to increasing atomic radius and shielding down the group, and higher nuclear charge across a period.',
        timestampStudent: '2025-06-27T15:23:00Z',
        timestampLecturer: '2025-06-27T16:05:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-3302')!,
        classId: 'BIO-3302',
        studentName: 'Tasya Ramadhani',
        studentArgument: 'In meiosis, why is genetic variation more significant than in mitosis?',
        lecturerResponse:
            'Excellent insight, Tasya. Crossing over and independent assortment in meiosis introduce variation, unlike mitosis which produces identical cells.',
        timestampStudent: '2025-06-25T14:40:00Z',
        timestampLecturer: '2025-06-25T15:20:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-2502')!,
        classId: 'PHY-2502',
        studentName: 'Yusuf Ardiansyah',
        studentArgument: 'I get confused when resistors are in both series and parallel. How do I know which formula to use?',
        lecturerResponse: 'That’s a common concern, Yusuf. First identify nodes and loops. I’ll give you a flowchart method in class tomorrow.',
        timestampStudent: '2025-06-29T10:30:00Z',
        timestampLecturer: '2025-06-29T11:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-2222')!,
        classId: 'GEO-2222',
        studentName: 'Intan Maharani',
        studentArgument: 'Why do volcanoes mostly form near tectonic plate boundaries?',
        lecturerResponse:
            'Excellent point, Intan. It’s due to subduction and rifting processes. Check our Moodle for an animation showing the Ring of Fire.',
        timestampStudent: '2025-06-23T09:05:00Z',
        timestampLecturer: '2025-06-23T10:47:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-1205')!,
        classId: 'PHY-1205',
        studentName: 'Joko Hartono',
        studentArgument: 'Can acceleration be negative even if an object is moving forward?',
        lecturerResponse: 'Yes, Joko. That’s called deceleration. I’ll demonstrate it with a velocity-time graph during practice.',
        timestampStudent: '2025-06-26T13:11:00Z',
        timestampLecturer: '2025-06-26T14:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-5533')!,
        classId: 'SCI-5533',
        studentName: 'Citra Melani',
        studentArgument: 'Why are polar regions warming faster than the equator?',
        lecturerResponse:
            'Great question, Citra. It’s due to Arctic amplification, where loss of ice reduces reflectivity, increasing heat absorption.',
        timestampStudent: '2025-06-28T07:55:00Z',
        timestampLecturer: '2025-06-28T09:18:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1211')!,
        classId: 'CHEM-1211',
        studentName: 'Hendra Saputra',
        studentArgument: 'Can you explain how neutralization helps in treating acidic soil?',
        lecturerResponse: 'Neutralization with basic compounds like lime helps restore soil pH, improving crop yield and health.',
        timestampStudent: '2025-06-27T12:31:00Z',
        timestampLecturer: '2025-06-27T13:45:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-4120')!,
        classId: 'BIO-4120',
        studentName: 'Lisa Septiani',
        studentArgument: 'How do angiosperms adapt better than gymnosperms in tropical climates?',
        lecturerResponse:
            'Their enclosed seeds and broader leaf structures give angiosperms better reproductive and survival traits in tropical climates.',
        timestampStudent: '2025-06-25T10:27:00Z',
        timestampLecturer: '2025-06-25T11:10:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-2098')!,
        classId: 'SCI-2098',
        studentName: 'Zaki Nurman',
        studentArgument: 'Is solar energy truly sustainable if panel production emits carbon?',
        lecturerResponse:
            'Lifecycle analysis shows solar panels offset their production emissions after a few years of operation, making them net positive.',
        timestampStudent: '2025-06-24T16:00:00Z',
        timestampLecturer: '2025-06-24T16:45:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-1015')!,
        classId: 'BIO-1015',
        studentName: 'Nadia Rahma',
        studentArgument: 'Do bones store more than just calcium?',
        lecturerResponse: 'Yes, bones also store phosphorus and contain marrow that produces blood cells, playing a critical role in homeostasis.',
        timestampStudent: '2025-06-30T10:00:00Z',
        timestampLecturer: '2025-06-30T11:30:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-8787')!,
        classId: 'GEO-8787',
        studentName: 'Farhan Husein',
        studentArgument: 'Is there any way to predict earthquakes near transform faults?',
        lecturerResponse: 'There’s no exact method yet, but seismic sensors and AI-based early warnings are improving rapidly.',
        timestampStudent: '2025-06-30T14:18:00Z',
        timestampLecturer: '2025-06-30T15:05:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-2920')!,
        classId: 'CHEM-2920',
        studentName: 'Siti Marlina',
        studentArgument: 'How do electron-dot diagrams help explain bonding?',
        lecturerResponse: 'They help visualize valence electrons, making it easier to predict bonding types and molecule structures.',
        timestampStudent: '2025-06-29T08:22:00Z',
        timestampLecturer: '2025-06-29T09:01:00Z',
    },
    // Additional discussionThreads entries
    {
        ...forumContents.find((f) => f.courseId === 'PHY-2502')!,
        classId: 'PHY-2502',
        studentName: 'Rizky Handayani',
        studentArgument: 'If the net force is zero, does it always mean an object is at rest?',
        lecturerResponse: 'Not necessarily, Rizky. It could be moving at constant velocity. We’ll clarify this distinction with Newton’s first law.',
        timestampStudent: '2025-06-29T12:10:00Z',
        timestampLecturer: '2025-06-29T13:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1103')!,
        classId: 'CHEM-1103',
        studentName: 'Daniel Surya',
        studentArgument: 'Why are noble gases generally unreactive?',
        lecturerResponse: 'Good observation, Daniel. Their outermost electron shells are full, making them stable and unlikely to form bonds.',
        timestampStudent: '2025-06-27T09:00:00Z',
        timestampLecturer: '2025-06-27T10:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-2201')!,
        classId: 'BIO-2201',
        studentName: 'Salsa Fitriani',
        studentArgument: 'Do plants use ATP during photosynthesis?',
        lecturerResponse: 'Yes, Salsa. ATP is produced in the light reactions and consumed during the Calvin cycle to fix carbon.',
        timestampStudent: '2025-06-26T10:10:00Z',
        timestampLecturer: '2025-06-26T10:50:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-3010')!,
        classId: 'GEO-3010',
        studentName: 'Ilham Fauzan',
        studentArgument: 'How does deforestation impact the carbon cycle?',
        lecturerResponse: 'Ilham, trees store carbon. Cutting them down releases CO₂, accelerating climate change.',
        timestampStudent: '2025-06-24T13:15:00Z',
        timestampLecturer: '2025-06-24T14:30:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1211')!,
        classId: 'CHEM-1211',
        studentName: 'Tari Wulandari',
        studentArgument: 'Why does acid rain damage buildings?',
        lecturerResponse: 'Tari, acid rain reacts with calcium carbonate in limestone, causing erosion. We’ll explore mitigation in next class.',
        timestampStudent: '2025-06-27T14:20:00Z',
        timestampLecturer: '2025-06-27T15:10:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-1205')!,
        classId: 'PHY-1205',
        studentName: 'Fahmi Ramadhan',
        studentArgument: 'Is weight the same as mass in physics?',
        lecturerResponse: 'Not quite, Fahmi. Mass is constant, but weight is force due to gravity. We’ll solve related problems soon.',
        timestampStudent: '2025-06-26T15:50:00Z',
        timestampLecturer: '2025-06-26T16:30:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-3302')!,
        classId: 'BIO-3302',
        studentName: 'Putri Lestari',
        studentArgument: 'How does independent assortment create genetic diversity?',
        lecturerResponse: 'Great point, Putri. It randomly shuffles chromosomes into gametes, ensuring varied offspring.',
        timestampStudent: '2025-06-25T15:40:00Z',
        timestampLecturer: '2025-06-25T16:20:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-2222')!,
        classId: 'GEO-2222',
        studentName: 'Adit Santoso',
        studentArgument: 'What causes tsunamis during undersea earthquakes?',
        lecturerResponse: 'Excellent question, Adit. Vertical displacement of seabed causes massive water movement. We’ll visualize this on Friday.',
        timestampStudent: '2025-06-23T11:00:00Z',
        timestampLecturer: '2025-06-23T12:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-2098')!,
        classId: 'SCI-2098',
        studentName: 'Nisa Kamila',
        studentArgument: 'Why aren’t solar panels widely adopted despite benefits?',
        lecturerResponse: 'Adoption is growing, Nisa, but barriers include high initial costs and infrastructure limits. Incentive programs are key.',
        timestampStudent: '2025-06-24T17:15:00Z',
        timestampLecturer: '2025-06-24T18:05:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-4321')!,
        classId: 'SCI-4321',
        studentName: 'Rendra Satria',
        studentArgument: 'Are biodegradable plastics truly eco-friendly?',
        lecturerResponse: 'Interesting query, Rendra. Some are, but others require industrial composting. We’ll compare types next week.',
        timestampStudent: '2025-06-28T10:20:00Z',
        timestampLecturer: '2025-06-28T11:40:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-1015')!,
        classId: 'BIO-1015',
        studentName: 'Kevin Wijaya',
        studentArgument: 'Why do we feel thirsty when we’re dehydrated, and how does the body regulate water balance?',
        lecturerResponse:
            "Excellent question, Kevin! Thirst is our body's primary signal. The hypothalamus detects changes in blood osmolality, triggering thirst and releasing ADH to regulate water reabsorption in the kidneys. We’ll delve deeper into osmoregulation in the next chapter.",
        timestampStudent: '2025-07-01T09:30:00Z',
        timestampLecturer: '2025-07-01T10:15:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-2920')!,
        classId: 'CHEM-2920',
        studentName: 'Maya Sari',
        studentArgument: 'Could you clarify the difference between strong and weak acids? I always get them mixed up.',
        lecturerResponse:
            'Absolutely, Maya. Strong acids completely ionize in water, like HCl, while weak acids, such as acetic acid, only partially ionize. The key is the extent of dissociation. We’ll practice identifying them in our lab session.',
        timestampStudent: '2025-07-02T11:00:00Z',
        timestampLecturer: '2025-07-02T11:45:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-8787')!,
        classId: 'GEO-8787',
        studentName: 'Eko Budiman',
        studentArgument: 'What impact do urban heat islands have on local weather patterns, especially in tropical cities?',
        lecturerResponse:
            "That's a very relevant topic, Eko. Urban heat islands can intensify local convection, leading to more frequent and intense thunderstorms. They also affect wind patterns. We’ll examine some case studies from Southeast Asian cities next week.",
        timestampStudent: '2025-07-02T13:40:00Z',
        timestampLecturer: '2025-07-02T14:25:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-2502')!,
        classId: 'PHY-2502',
        studentName: 'Andi Pratama',
        studentArgument: "I'm struggling to understand how Lenz's Law applies in real-world scenarios. Can you give a practical example?",
        lecturerResponse:
            "Good point, Andi. Lenz's Law is crucial for understanding electromagnetic induction. Think about induction cooktops – they use an induced current to generate heat, opposing the change in magnetic flux. We’ll have a demonstration using coils and magnets to visualize this clearly.",
        timestampStudent: '2025-07-01T15:00:00Z',
        timestampLecturer: '2025-07-01T15:50:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-5533')!,
        classId: 'SCI-5533',
        studentName: 'Dina Permata',
        studentArgument:
            'With so much talk about climate change, what are some realistic individual actions we can take that actually make a difference?',
        lecturerResponse:
            "Dina, that’s a critical question. While systemic change is vital, individual actions like reducing consumption, supporting renewable energy, and advocating for policy changes do contribute. We'll discuss the cumulative impact of these actions and how to effectively participate in advocacy in our next seminar.",
        timestampStudent: '2025-07-03T08:10:00Z',
        timestampLecturer: '2025-07-03T09:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-4321')!,
        classId: 'SCI-4321',
        studentName: 'Alya Nurhaliza',
        studentArgument: 'I think local factories still dump chemical waste into rivers because the cost of proper disposal is too high.',
        lecturerResponse:
            'Alya, that’s a valid observation. Economic barriers are a major reason. In our next session, we’ll review cost-effective sustainable waste treatment alternatives being piloted in Southeast Asia.',
        timestampStudent: '2025-06-28T09:14:00Z',
        timestampLecturer: '2025-06-28T11:23:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-2201')!,
        classId: 'BIO-2201',
        studentName: 'Bima Prasetyo',
        studentArgument: 'Can you explain why the Calvin cycle is light-independent even though it still indirectly depends on light?',
        lecturerResponse:
            'Great question, Bima. It’s light-independent because it doesn’t require photons directly, but it uses ATP and NADPH from the light-dependent reactions.',
        timestampStudent: '2025-06-26T08:49:00Z',
        timestampLecturer: '2025-06-26T09:15:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-3010')!,
        classId: 'GEO-3010',
        studentName: 'Dewi Anggraini',
        studentArgument: 'How accurate are computer simulations in predicting future greenhouse gas effects?',
        lecturerResponse:
            'Dewi, climate models have limitations, but they’re based on decades of reliable data and constantly improved. They are essential tools for policy decisions globally.',
        timestampStudent: '2025-06-24T10:00:00Z',
        timestampLecturer: '2025-06-24T12:08:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1103')!,
        classId: 'CHEM-1103',
        studentName: 'Rafi Ilham',
        studentArgument: 'Why does electronegativity decrease down a group but increase across a period?',
        lecturerResponse:
            'Nice reasoning, Rafi. It’s due to increasing atomic radius and shielding down the group, and higher nuclear charge across a period.',
        timestampStudent: '2025-06-27T15:23:00Z',
        timestampLecturer: '2025-06-27T16:05:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-3302')!,
        classId: 'BIO-3302',
        studentName: 'Tasya Ramadhani',
        studentArgument: 'In meiosis, why is genetic variation more significant than in mitosis?',
        lecturerResponse:
            'Excellent insight, Tasya. Crossing over and independent assortment in meiosis introduce variation, unlike mitosis which produces identical cells.',
        timestampStudent: '2025-06-25T14:40:00Z',
        timestampLecturer: '2025-06-25T15:20:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-2502')!,
        classId: 'PHY-2502',
        studentName: 'Yusuf Ardiansyah',
        studentArgument: 'I get confused when resistors are in both series and parallel. How do I know which formula to use?',
        lecturerResponse: 'That’s a common concern, Yusuf. First identify nodes and loops. I’ll give you a flowchart method in class tomorrow.',
        timestampStudent: '2025-06-29T10:30:00Z',
        timestampLecturer: '2025-06-29T11:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-2222')!,
        classId: 'GEO-2222',
        studentName: 'Intan Maharani',
        studentArgument: 'Why do volcanoes mostly form near tectonic plate boundaries?',
        lecturerResponse:
            'Excellent point, Intan. It’s due to subduction and rifting processes. Check our Moodle for an animation showing the Ring of Fire.',
        timestampStudent: '2025-06-23T09:05:00Z',
        timestampLecturer: '2025-06-23T10:47:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-1205')!,
        classId: 'PHY-1205',
        studentName: 'Joko Hartono',
        studentArgument: 'Can acceleration be negative even if an object is moving forward?',
        lecturerResponse: 'Yes, Joko. That’s called deceleration. I’ll demonstrate it with a velocity-time graph during practice.',
        timestampStudent: '2025-06-26T13:11:00Z',
        timestampLecturer: '2025-06-26T14:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-5533')!,
        classId: 'SCI-5533',
        studentName: 'Citra Melani',
        studentArgument: 'Why are polar regions warming faster than the equator?',
        lecturerResponse:
            'Great question, Citra. It’s due to Arctic amplification, where loss of ice reduces reflectivity, increasing heat absorption.',
        timestampStudent: '2025-06-28T07:55:00Z',
        timestampLecturer: '2025-06-28T09:18:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1211')!,
        classId: 'CHEM-1211',
        studentName: 'Hendra Saputra',
        studentArgument: 'Can you explain how neutralization helps in treating acidic soil?',
        lecturerResponse: 'Neutralization with basic compounds like lime helps restore soil pH, improving crop yield and health.',
        timestampStudent: '2025-06-27T12:31:00Z',
        timestampLecturer: '2025-06-27T13:45:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-4120')!,
        classId: 'BIO-4120',
        studentName: 'Lisa Septiani',
        studentArgument: 'How do angiosperms adapt better than gymnosperms in tropical climates?',
        lecturerResponse:
            'Their enclosed seeds and broader leaf structures give angiosperms better reproductive and survival traits in tropical climates.',
        timestampStudent: '2025-06-25T10:27:00Z',
        timestampLecturer: '2025-06-25T11:10:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-2098')!,
        classId: 'SCI-2098',
        studentName: 'Zaki Nurman',
        studentArgument: 'Is solar energy truly sustainable if panel production emits carbon?',
        lecturerResponse:
            'Lifecycle analysis shows solar panels offset their production emissions after a few years of operation, making them net positive.',
        timestampStudent: '2025-06-24T16:00:00Z',
        timestampLecturer: '2025-06-24T16:45:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-1015')!,
        classId: 'BIO-1015',
        studentName: 'Nadia Rahma',
        studentArgument: 'Do bones store more than just calcium?',
        lecturerResponse: 'Yes, bones also store phosphorus and contain marrow that produces blood cells, playing a critical role in homeostasis.',
        timestampStudent: '2025-06-30T10:00:00Z',
        timestampLecturer: '2025-06-30T11:30:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-8787')!,
        classId: 'GEO-8787',
        studentName: 'Farhan Husein',
        studentArgument: 'Is there any way to predict earthquakes near transform faults?',
        lecturerResponse: 'There’s no exact method yet, but seismic sensors and AI-based early warnings are improving rapidly.',
        timestampStudent: '2025-06-30T14:18:00Z',
        timestampLecturer: '2025-06-30T15:05:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-2920')!,
        classId: 'CHEM-2920',
        studentName: 'Siti Marlina',
        studentArgument: 'How do electron-dot diagrams help explain bonding?',
        lecturerResponse: 'They help visualize valence electrons, making it easier to predict bonding types and molecule structures.',
        timestampStudent: '2025-06-29T08:22:00Z',
        timestampLecturer: '2025-06-29T09:01:00Z',
    },
    // Additional discussionThreads entries
    {
        ...forumContents.find((f) => f.courseId === 'PHY-2502')!,
        classId: 'PHY-2502',
        studentName: 'Rizky Handayani',
        studentArgument: 'If the net force is zero, does it always mean an object is at rest?',
        lecturerResponse: 'Not necessarily, Rizky. It could be moving at constant velocity. We’ll clarify this distinction with Newton’s first law.',
        timestampStudent: '2025-06-29T12:10:00Z',
        timestampLecturer: '2025-06-29T13:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1103')!,
        classId: 'CHEM-1103',
        studentName: 'Daniel Surya',
        studentArgument: 'Why are noble gases generally unreactive?',
        lecturerResponse: 'Good observation, Daniel. Their outermost electron shells are full, making them stable and unlikely to form bonds.',
        timestampStudent: '2025-06-27T09:00:00Z',
        timestampLecturer: '2025-06-27T10:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-2201')!,
        classId: 'BIO-2201',
        studentName: 'Salsa Fitriani',
        studentArgument: 'Do plants use ATP during photosynthesis?',
        lecturerResponse: 'Yes, Salsa. ATP is produced in the light reactions and consumed during the Calvin cycle to fix carbon.',
        timestampStudent: '2025-06-26T10:10:00Z',
        timestampLecturer: '2025-06-26T10:50:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-3010')!,
        classId: 'GEO-3010',
        studentName: 'Ilham Fauzan',
        studentArgument: 'How does deforestation impact the carbon cycle?',
        lecturerResponse: 'Ilham, trees store carbon. Cutting them down releases CO₂, accelerating climate change.',
        timestampStudent: '2025-06-24T13:15:00Z',
        timestampLecturer: '2025-06-24T14:30:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1211')!,
        classId: 'CHEM-1211',
        studentName: 'Tari Wulandari',
        studentArgument: 'Why does acid rain damage buildings?',
        lecturerResponse: 'Tari, acid rain reacts with calcium carbonate in limestone, causing erosion. We’ll explore mitigation in next class.',
        timestampStudent: '2025-06-27T14:20:00Z',
        timestampLecturer: '2025-06-27T15:10:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-1205')!,
        classId: 'PHY-1205',
        studentName: 'Fahmi Ramadhan',
        studentArgument: 'Is weight the same as mass in physics?',
        lecturerResponse: 'Not quite, Fahmi. Mass is constant, but weight is force due to gravity. We’ll solve related problems soon.',
        timestampStudent: '2025-06-26T15:50:00Z',
        timestampLecturer: '2025-06-26T16:30:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-3302')!,
        classId: 'BIO-3302',
        studentName: 'Putri Lestari',
        studentArgument: 'How does independent assortment create genetic diversity?',
        lecturerResponse: 'Great point, Putri. It randomly shuffles chromosomes into gametes, ensuring varied offspring.',
        timestampStudent: '2025-06-25T15:40:00Z',
        timestampLecturer: '2025-06-25T16:20:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-2222')!,
        classId: 'GEO-2222',
        studentName: 'Adit Santoso',
        studentArgument: 'What causes tsunamis during undersea earthquakes?',
        lecturerResponse: 'Excellent question, Adit. Vertical displacement of seabed causes massive water movement. We’ll visualize this on Friday.',
        timestampStudent: '2025-06-23T11:00:00Z',
        timestampLecturer: '2025-06-23T12:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-2098')!,
        classId: 'SCI-2098',
        studentName: 'Nisa Kamila',
        studentArgument: 'Why aren’t solar panels widely adopted despite benefits?',
        lecturerResponse: 'Adoption is growing, Nisa, but barriers include high initial costs and infrastructure limits. Incentive programs are key.',
        timestampStudent: '2025-06-24T17:15:00Z',
        timestampLecturer: '2025-06-24T18:05:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-4321')!,
        classId: 'SCI-4321',
        studentName: 'Rendra Satria',
        studentArgument: 'Are biodegradable plastics truly eco-friendly?',
        lecturerResponse: 'Interesting query, Rendra. Some are, but others require industrial composting. We’ll compare types next week.',
        timestampStudent: '2025-06-28T10:20:00Z',
        timestampLecturer: '2025-06-28T11:40:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-1015')!,
        classId: 'BIO-1015',
        studentName: 'Kevin Wijaya',
        studentArgument: 'Why do we feel thirsty when we’re dehydrated, and how does the body regulate water balance?',
        lecturerResponse:
            "Excellent question, Kevin! Thirst is our body's primary signal. The hypothalamus detects changes in blood osmolality, triggering thirst and releasing ADH to regulate water reabsorption in the kidneys. We’ll delve deeper into osmoregulation in the next chapter.",
        timestampStudent: '2025-07-01T09:30:00Z',
        timestampLecturer: '2025-07-01T10:15:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-2920')!,
        classId: 'CHEM-2920',
        studentName: 'Maya Sari',
        studentArgument: 'Could you clarify the difference between strong and weak acids? I always get them mixed up.',
        lecturerResponse:
            'Absolutely, Maya. Strong acids completely ionize in water, like HCl, while weak acids, such as acetic acid, only partially ionize. The key is the extent of dissociation. We’ll practice identifying them in our lab session.',
        timestampStudent: '2025-07-02T11:00:00Z',
        timestampLecturer: '2025-07-02T11:45:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-8787')!,
        classId: 'GEO-8787',
        studentName: 'Eko Budiman',
        studentArgument: 'What impact do urban heat islands have on local weather patterns, especially in tropical cities?',
        lecturerResponse:
            "That's a very relevant topic, Eko. Urban heat islands can intensify local convection, leading to more frequent and intense thunderstorms. They also affect wind patterns. We’ll examine some case studies from Southeast Asian cities next week.",
        timestampStudent: '2025-07-02T13:40:00Z',
        timestampLecturer: '2025-07-02T14:25:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-2502')!,
        classId: 'PHY-2502',
        studentName: 'Andi Pratama',
        studentArgument: "I'm struggling to understand how Lenz's Law applies in real-world scenarios. Can you give a practical example?",
        lecturerResponse:
            "Good point, Andi. Lenz's Law is crucial for understanding electromagnetic induction. Think about induction cooktops – they use an induced current to generate heat, opposing the change in magnetic flux. We’ll have a demonstration using coils and magnets to visualize this clearly.",
        timestampStudent: '2025-07-01T15:00:00Z',
        timestampLecturer: '2025-07-01T15:50:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-5533')!,
        classId: 'SCI-5533',
        studentName: 'Dina Permata',
        studentArgument:
            'With so much talk about climate change, what are some realistic individual actions we can take that actually make a difference?',
        lecturerResponse:
            "Dina, that’s a critical question. While systemic change is vital, individual actions like reducing consumption, supporting renewable energy, and advocating for policy changes do contribute. We'll discuss the cumulative impact of these actions and how to effectively participate in advocacy in our next seminar.",
        timestampStudent: '2025-07-03T08:10:00Z',
        timestampLecturer: '2025-07-03T09:00:00Z',
    },
    // --- Session 1: Environmental Science & Biology ---
    {
        ...forumContents.find((f) => f.courseId === 'SCI-4321')!,
        classId: 'SCI-4321',
        studentName: 'Fajar Kurniawan',
        studentArgument: 'Given the push for electric vehicles, what are the environmental implications of lithium mining and battery disposal?',
        lecturerResponse:
            "Fajar, that's an excellent point. While EVs reduce tailpipe emissions, the lifecycle impact of batteries is a key concern. We'll examine the challenges of sustainable mining practices and current recycling technologies in our next module on green technologies.",
        timestampStudent: '2025-07-03T10:00:00Z',
        timestampLecturer: '2025-07-03T11:05:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-2201')!,
        classId: 'BIO-2201',
        studentName: 'Rina Wijayanti',
        studentArgument: 'Why is genetic engineering so controversial, and what are its potential benefits in agriculture?',
        lecturerResponse:
            "Rina, the controversy stems from ethical and safety concerns, but benefits in agriculture include enhanced crop yields, disease resistance, and improved nutritional value. We'll have a guest lecture next week from a bioethicist to explore this further.",
        timestampStudent: '2025-07-03T11:30:00Z',
        timestampLecturer: '2025-07-03T12:20:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-3010')!,
        classId: 'GEO-3010',
        studentName: 'Galih Perkasa',
        studentArgument: 'How do changing ocean currents impact global climate, and are there models predicting these shifts?',
        lecturerResponse:
            "Galih, ocean currents are massive heat transporters, so even small changes can significantly alter regional climates. Yes, sophisticated ocean-atmosphere coupled models are used, though predicting exact shifts remains a complex challenge. We'll analyze some of these model outputs in our next lab.",
        timestampStudent: '2025-07-03T14:00:00Z',
        timestampLecturer: '2025-07-03T15:10:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-1103')!,
        classId: 'CHEM-1103',
        studentName: 'Sinta Dewi',
        studentArgument: 'When balancing redox reactions, why is it crucial to consider both mass and charge conservation?',
        lecturerResponse:
            "Sinta, that's fundamental! Mass conservation ensures all atoms are accounted for, and charge conservation ensures the number of electrons lost equals those gained. Without both, the reaction equation wouldn't accurately represent the chemical change. We'll work through more complex examples next session.",
        timestampStudent: '2025-07-03T16:30:00Z',
        timestampLecturer: '2025-07-03T17:15:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-3302')!,
        classId: 'BIO-3302',
        studentName: 'Yoga Pratama',
        studentArgument: 'Can gene editing techniques like CRISPR entirely eliminate genetic diseases in humans, or are there limitations?',
        lecturerResponse:
            "Yoga, CRISPR holds immense promise for treating genetic diseases, but it faces significant technical and ethical limitations, including off-target edits and germline editing concerns. It's a rapidly evolving field, and we'll dedicate a discussion to its current capabilities and future prospects.",
        timestampStudent: '2025-07-03T09:00:00Z',
        timestampLecturer: '2025-07-03T09:45:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-2222')!,
        classId: 'GEO-2222',
        studentName: 'Linda Susanti',
        studentArgument: 'How do glaciologists measure ice sheet melt rates, and what are the biggest challenges in getting accurate data?',
        lecturerResponse:
            'Linda, glaciologists use a combination of satellite altimetry, ground-penetrating radar, and direct ice core measurements. The biggest challenges are the vast scale, harsh conditions, and the complex interactions between ice, ocean, and atmosphere. We’ll look at some recent research papers on this topic.',
        timestampStudent: '2025-07-04T10:00:00Z',
        timestampLecturer: '2025-07-04T10:55:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'PHY-1205')!,
        classId: 'PHY-1205',
        studentName: 'Dian Permana',
        studentArgument: 'If light has both wave and particle properties, how do we determine which one dominates in a given experiment?',
        lecturerResponse:
            "Dian, that's the essence of wave-particle duality! It depends on the experimental setup. For example, diffraction experiments show wave-like behavior, while the photoelectric effect demonstrates particle-like behavior. We'll delve into specific experiments that highlight this in our quantum mechanics intro.",
        timestampStudent: '2025-07-04T11:45:00Z',
        timestampLecturer: '2025-07-04T12:30:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'GEO-8787')!,
        classId: 'GEO-8787',
        studentName: 'Rudi Santoso',
        studentArgument:
            'What are the main factors contributing to land subsidence in coastal cities like Jakarta, and what are the long-term solutions?',
        lecturerResponse:
            "Rudi, land subsidence in Jakarta is primarily due to excessive groundwater extraction, coupled with the natural compaction of alluvial sediments. Long-term solutions involve diversifying water sources, promoting rainwater harvesting, and potentially managed aquifer recharge. This is a critical issue we'll be discussing in depth.",
        timestampStudent: '2025-07-04T14:00:00Z',
        timestampLecturer: '2025-07-04T15:10:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-2098')!,
        classId: 'SCI-2098',
        studentName: 'Ayu Lestari',
        studentArgument: 'How can small-scale renewable energy projects empower rural communities in developing countries?',
        lecturerResponse:
            "Ayu, small-scale renewables like micro-hydro, solar home systems, or biomass digesters can significantly improve quality of life by providing reliable electricity, reducing fuel costs, and even supporting local economic activities. We'll explore case studies from various regions showing their impact next week.",
        timestampStudent: '2025-07-04T09:15:00Z',
        timestampLecturer: '2025-07-04T10:00:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-4120')!,
        classId: 'BIO-4120',
        studentName: 'Jessica Putri',
        studentArgument: 'How do neurotoxins affect the nervous system at a molecular level, and what are some common examples?',
        lecturerResponse:
            "Jessica, neurotoxins disrupt nerve impulse transmission by interfering with ion channels, neurotransmitter release, or receptor binding. Examples include botulinum toxin and tetrodotoxin. We'll analyze specific mechanisms in our neurobiology section next month.",
        timestampStudent: '2025-07-05T11:00:00Z',
        timestampLecturer: '2025-07-05T11:55:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'CHEM-2920')!,
        classId: 'CHEM-2920',
        studentName: 'Kevin Santoso',
        studentArgument: 'What makes certain chemical reactions exothermic and others endothermic? Is it just about bond breaking and forming?',
        lecturerResponse:
            "Excellent question, Kevin. It's primarily about the energy difference between bond breaking (requires energy) and bond forming (releases energy). If more energy is released than absorbed, it's exothermic. If more is absorbed, it's endothermic. We'll quantify this with enthalpy calculations in our thermodynamics chapter.",
        timestampStudent: '2025-07-05T13:20:00Z',
        timestampLecturer: '2025-07-05T14:10:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'SCI-4321')!,
        classId: 'SCI-4321',
        studentName: 'Putra Darmawan',
        studentArgument:
            'Considering global food security, how effective are vertical farms and hydroponics in providing sustainable food sources for urban areas?',
        lecturerResponse:
            "Putra, vertical farming and hydroponics offer significant advantages in urban settings like reduced land use, water efficiency, and local production. However, energy consumption for lighting can be a challenge. We'll review current operational models and future innovations in sustainable agriculture.",
        timestampStudent: '2025-07-05T14:50:00Z',
        timestampLecturer: '2025-07-05T15:45:00Z',
    },
    {
        ...forumContents.find((f) => f.courseId === 'BIO-1015')!,
        classId: 'BIO-1015',
        studentName: 'Sarah Amalia',
        studentArgument:
            'How does the human immune system distinguish between "self" and "non-self" cells, and what happens when this process fails?',
        lecturerResponse:
            "Sarah, the immune system uses complex molecular markers on cell surfaces, primarily MHC proteins, to differentiate. When this process fails, it can lead to autoimmune diseases where the body attacks its own tissues. We'll explore specific examples and treatments in our immunology section.",
        timestampStudent: '2025-07-05T10:00:00Z',
        timestampLecturer: '2025-07-05T10:50:00Z',
    },
];
