export type Assignment = {
    title: string;
    courseName: string;
    courseId: string;
    classId: string;
    dueDate: string;
    type: string;
    description: string;
    link: string;
};

export const assignmentBankQuestion: Assignment[] = [
    {
        title: 'Science Topic Question 1',
        courseName: 'Science',
        courseId: 'SCI-4321',
        classId: 'XI-Scie-2',
        dueDate: '',
        type: 'Written Report',
        description: 'Explain the scientific principles behind climate change and how it affects biodiversity across different ecosystems.',
        link: '/assignment/science/SCI-4321',
    },
    {
        title: 'Science Topic Question 2',
        courseName: 'Science',
        courseId: 'SCI-4321',
        classId: 'XII-Scie-4',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Describe how human activities contribute to the depletion of the ozone layer. Include chemical equations and real-world data.',
        link: '/assignment/science/SCI-4321',
    },
    {
        title: 'Science Topic Question 3',
        courseName: 'Science',
        courseId: 'SCI-4321',
        classId: 'X-Scie-3',
        dueDate: '',
        type: 'True/False',
        description: 'Analyze the relationship between carbon cycle disruption and global warming using satellite data trends.',
        link: '/assignment/science/SCI-4321',
    },
    {
        title: 'Biology Topic Question 1',
        courseName: 'Biology',
        courseId: 'BIO-2201',
        classId: 'X-Biol-1',
        dueDate: '',
        type: 'True/False',
        description: 'Compare and contrast the stages of mitosis and meiosis. Include diagrams and note biological significance.',
        link: '/assignment/biology/BIO-2201',
    },
    {
        title: 'Biology Topic Question 2',
        courseName: 'Biology',
        courseId: 'BIO-2201',
        classId: 'X-Biol-2',
        dueDate: '',
        type: 'Short Answer',
        description: 'Explain the process of DNA replication, including the roles of enzymes such as DNA polymerase and ligase.',
        link: '/assignment/biology/BIO-2201',
    },
    {
        title: 'Biology Topic Question 3',
        courseName: 'Biology',
        courseId: 'BIO-2201',
        classId: 'XI-Biol-4',
        dueDate: '',
        type: 'Essay',
        description: 'Describe the mechanisms of evolution as proposed by Darwin and provide evidence supporting natural selection.',
        link: '/assignment/biology/BIO-2201',
    },
    {
        title: 'Geography Topic Question 1',
        courseName: 'Geography',
        courseId: 'GEO-3010',
        classId: 'XII-Geog-4',
        dueDate: '',
        type: 'Short Answer',
        description: 'Describe the effects of urbanization on local climates and hydrological cycles using a specific case study.',
        link: '/assignment/geography/GEO-3010',
    },
    {
        title: 'Geography Topic Question 2',
        courseName: 'Geography',
        courseId: 'GEO-3010',
        classId: 'XI-Geog-3',
        dueDate: '',
        type: 'Written Report',
        description: 'Explain the formation and impact of tropical cyclones on coastal regions, including hazard mitigation strategies.',
        link: '/assignment/geography/GEO-3010',
    },
    {
        title: 'Geography Topic Question 3',
        courseName: 'Geography',
        courseId: 'GEO-3010',
        classId: 'X-Geog-2',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Discuss the concept of plate tectonics and its role in the distribution of earthquakes and volcanoes worldwide.',
        link: '/assignment/geography/GEO-3010',
    },
    {
        title: 'Chemistry Topic Question 1',
        courseName: 'Chemistry',
        courseId: 'CHEM-1103',
        classId: 'X-Chem-1',
        dueDate: '',
        type: 'Essay',
        description: 'Balance the following redox reaction and explain the oxidation and reduction processes involved.',
        link: '/assignment/chemistry/CHEM-1103#q1',
    },
    {
        title: 'Chemistry Topic Question 2',
        courseName: 'Chemistry',
        courseId: 'CHEM-1103',
        classId: 'XII-Chem-2',
        dueDate: '',
        type: 'Essay',
        description: 'Describe the trends in atomic radius, ionization energy, and electronegativity across a period and down a group.',
        link: '/assignment/chemistry/CHEM-1103#q2',
    },
    {
        title: 'Chemistry Topic Question 3',
        courseName: 'Chemistry',
        courseId: 'CHEM-1103',
        classId: 'XII-Chem-2',
        dueDate: '',
        type: 'Written Report',
        description: "Explain Le Chatelier's Principle using industrial examples such as the Haber Process.",
        link: '/assignment/chemistry/CHEM-1103#q3',
    },
    {
        title: 'Biology Topic Question 1',
        courseName: 'Biology',
        courseId: 'BIO-3302',
        classId: 'XI-Biol-2',
        dueDate: '',
        type: 'Written Report',
        description: 'Compare and contrast the stages of mitosis and meiosis. Include diagrams and note biological significance.',
        link: '/assignment/biology/BIO-3302#q1',
    },
    {
        title: 'Biology Topic Question 2',
        courseName: 'Biology',
        courseId: 'BIO-3302',
        classId: 'XII-Biol-3',
        dueDate: '',
        type: 'Written Report',
        description: 'Explain the process of DNA replication, including the roles of enzymes such as DNA polymerase and ligase.',
        link: '/assignment/biology/BIO-3302#q2',
    },
    {
        title: 'Biology Topic Question 3',
        courseName: 'Biology',
        courseId: 'BIO-3302',
        classId: 'XI-Biol-2',
        dueDate: '',
        type: 'Short Answer',
        description: 'Describe the mechanisms of evolution as proposed by Darwin and provide evidence supporting natural selection.',
        link: '/assignment/biology/BIO-3302#q3',
    },
    {
        title: 'Physics Topic Question 1',
        courseName: 'Physics',
        courseId: 'PHY-2502',
        classId: 'XI-Phys-2',
        dueDate: '',
        type: 'Essay',
        description: 'Using qton\u2019s Laws, explain the motion of a car on an inclined plane with and without friction.',
        link: '/assignment/physics/PHY-2502#q1',
    },
    {
        title: 'Physics Topic Question 2',
        courseName: 'Physics',
        courseId: 'PHY-2502',
        classId: 'XI-Phys-3',
        dueDate: '',
        type: 'Essay',
        description: 'Describe the energy transformations in a simple pendulum and derive the period formula.',
        link: '/assignment/physics/PHY-2502#q2',
    },
    {
        title: 'Physics Topic Question 3',
        courseName: 'Physics',
        courseId: 'PHY-2502',
        classId: 'XI-Phys-4',
        dueDate: '',
        type: 'Written Report',
        description: 'Explain how lenses form images using ray diagrams, and distinguish between real and virtual images.',
        link: '/assignment/physics/PHY-2502#q3',
    },
    {
        title: 'Physics Topic Question 1',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'XII-Phys-1',
        dueDate: '',
        type: 'Short Answer',
        description: 'Using qton\u2019s Laws, explain the motion of a car on an inclined plane with and without friction.',
        link: '/assignment/physics/PHY-1205#q1',
    },
    {
        title: 'Physics Topic Question 2',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'X-Phys-4',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Describe the energy transformations in a simple pendulum and derive the period formula.',
        link: '/assignment/physics/PHY-1205#q2',
    },
    {
        title: 'Physics Topic Question 3',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'XI-Phys-2',
        dueDate: '',
        type: 'Short Answer',
        description: 'Explain how lenses form images using ray diagrams, and distinguish between real and virtual images.',
        link: '/assignment/physics/PHY-1205#q3',
    },
    {
        title: 'Geography Topic Question 1',
        courseName: 'Geography',
        courseId: 'GEO-2222',
        classId: 'X-Geog-1',
        dueDate: '',
        type: 'Written Report',
        description: 'Describe the effects of urbanization on local climates and hydrological cycles using a specific case study.',
        link: '/assignment/geography/GEO-2222#q1',
    },
    {
        title: 'Geography Topic Question 2',
        courseName: 'Geography',
        courseId: 'GEO-2222',
        classId: 'XI-Geog-4',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Explain the formation and impact of tropical cyclones on coastal regions, including hazard mitigation strategies.',
        link: '/assignment/geography/GEO-2222#q2',
    },
    {
        title: 'Geography Topic Question 3',
        courseName: 'Geography',
        courseId: 'GEO-2222',
        classId: 'XII-Geog-3',
        dueDate: '',
        type: 'Written Report',
        description: 'Discuss the concept of plate tectonics and its role in the distribution of earthquakes and volcanoes worldwide.',
        link: '/assignment/geography/GEO-2222#q3',
    },
    {
        title: 'Science Topic Question 1',
        courseName: 'Science',
        courseId: 'SCI-5533',
        classId: 'XI-Scie-4',
        dueDate: '',
        type: 'Essay',
        description: 'Explain the scientific principles behind climate change and how it affects biodiversity across different ecosystems.',
        link: '/assignment/science/SCI-5533#q1',
    },
    {
        title: 'Science Topic Question 2',
        courseName: 'Science',
        courseId: 'SCI-5533',
        classId: 'X-Scie-3',
        dueDate: '',
        type: 'Essay',
        description: 'Describe how human activities contribute to the depletion of the ozone layer. Include chemical equations and real-world data.',
        link: '/assignment/science/SCI-5533#q2',
    },
    {
        title: 'Science Topic Question 3',
        courseName: 'Science',
        courseId: 'SCI-5533',
        classId: 'XII-Scie-4',
        dueDate: '',
        type: 'True/False',
        description: 'Analyze the relationship between carbon cycle disruption and global warming using satellite data trends.',
        link: '/assignment/science/SCI-5533#q3',
    },
    {
        title: 'Chemistry Topic Question 1',
        courseName: 'Chemistry',
        courseId: 'CHEM-1211',
        classId: 'XII-Chem-3',
        dueDate: '',
        type: 'Essay',
        description: 'Balance the following redox reaction and explain the oxidation and reduction processes involved.',
        link: '/assignment/chemistry/CHEM-1211#q1',
    },
    {
        title: 'Chemistry Topic Question 2',
        courseName: 'Chemistry',
        courseId: 'CHEM-1211',
        classId: 'X-Chem-1',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Describe the trends in atomic radius, ionization energy, and electronegativity across a period and down a group.',
        link: '/assignment/chemistry/CHEM-1211#q2',
    },
    {
        title: 'Chemistry Topic Question 3',
        courseName: 'Chemistry',
        courseId: 'CHEM-1211',
        classId: 'X-Chem-2',
        dueDate: '',
        type: 'Essay',
        description: "Explain Le Chatelier's Principle using industrial examples such as the Haber Process.",
        link: '/assignment/chemistry/CHEM-1211#q3',
    },
    {
        title: 'Biology Topic Question 1',
        courseName: 'Biology',
        courseId: 'BIO-4120',
        classId: 'XII-Biol-4',
        dueDate: '',
        type: 'Essay',
        description: 'Compare and contrast the stages of mitosis and meiosis. Include diagrams and note biological significance.',
        link: '/assignment/biology/BIO-4120#q1',
    },
    {
        title: 'Biology Topic Question 2',
        courseName: 'Biology',
        courseId: 'BIO-4120',
        classId: 'XII-Biol-1',
        dueDate: '',
        type: 'Written Report',
        description: 'Explain the process of DNA replication, including the roles of enzymes such as DNA polymerase and ligase.',
        link: '/assignment/biology/BIO-4120#q2',
    },
    {
        title: 'Biology Topic Question 3',
        courseName: 'Biology',
        courseId: 'BIO-4120',
        classId: 'XII-Biol-3',
        dueDate: '',
        type: 'Essay',
        description: 'Describe the mechanisms of evolution as proposed by Darwin and provide evidence supporting natural selection.',
        link: '/assignment/biology/BIO-4120#q3',
    },
    {
        title: 'Science Topic Question 1',
        courseName: 'Science',
        courseId: 'SCI-2098',
        classId: 'XII-Scie-3',
        dueDate: '',
        type: 'Written Report',
        description: 'Explain the scientific principles behind climate change and how it affects biodiversity across different ecosystems.',
        link: '/assignment/science/SCI-2098#q1',
    },
    {
        title: 'Science Topic Question 2',
        courseName: 'Science',
        courseId: 'SCI-2098',
        classId: 'X-Scie-4',
        dueDate: '',
        type: 'Written Report',
        description: 'Describe how human activities contribute to the depletion of the ozone layer. Include chemical equations and real-world data.',
        link: '/assignment/science/SCI-2098#q2',
    },
    {
        title: 'Science Topic Question 3',
        courseName: 'Science',
        courseId: 'SCI-2098',
        classId: 'XII-Scie-3',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Analyze the relationship between carbon cycle disruption and global warming using satellite data trends.',
        link: '/assignment/science/SCI-2098#q3',
    },
    {
        title: 'Biology Topic Question 1',
        courseName: 'Biology',
        courseId: 'BIO-1015',
        classId: 'XII-Biol-4',
        dueDate: '',
        type: 'Written Report',
        description: 'Compare and contrast the stages of mitosis and meiosis. Include diagrams and note biological significance.',
        link: '/assignment/biology/BIO-1015#q1',
    },
    {
        title: 'Biology Topic Question 2',
        courseName: 'Biology',
        courseId: 'BIO-1015',
        classId: 'XI-Biol-3',
        dueDate: '',
        type: 'Essay',
        description: 'Explain the process of DNA replication, including the roles of enzymes such as DNA polymerase and ligase.',
        link: '/assignment/biology/BIO-1015#q2',
    },
    {
        title: 'Biology Topic Question 3',
        courseName: 'Biology',
        courseId: 'BIO-1015',
        classId: 'XI-Biol-3',
        dueDate: '',
        type: 'Short Answer',
        description: 'Describe the mechanisms of evolution as proposed by Darwin and provide evidence supporting natural selection.',
        link: '/assignment/biology/BIO-1015#q3',
    },
    {
        title: 'Geography Topic Question 1',
        courseName: 'Geography',
        courseId: 'GEO-8787',
        classId: 'X-Geog-4',
        dueDate: '',
        type: 'Short Answer',
        description: 'Describe the effects of urbanization on local climates and hydrological cycles using a specific case study.',
        link: '/assignment/geography/GEO-8787#q1',
    },
    {
        title: 'Geography Topic Question 2',
        courseName: 'Geography',
        courseId: 'GEO-8787',
        classId: 'XI-Geog-4',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Explain the formation and impact of tropical cyclones on coastal regions, including hazard mitigation strategies.',
        link: '/assignment/geography/GEO-8787#q2',
    },
    {
        title: 'Geography Topic Question 3',
        courseName: 'Geography',
        courseId: 'GEO-8787',
        classId: 'XII-Geog-2',
        dueDate: '',
        type: 'Essay',
        description: 'Discuss the concept of plate tectonics and its role in the distribution of earthquakes and volcanoes worldwide.',
        link: '/assignment/geography/GEO-8787#q3',
    },
    {
        title: 'Chemistry Topic Question 1',
        courseName: 'Chemistry',
        courseId: 'CHEM-2920',
        classId: 'XII-Chem-4',
        dueDate: '',
        type: 'Short Answer',
        description: 'Balance the following redox reaction and explain the oxidation and reduction processes involved.',
        link: '/assignment/chemistry/CHEM-2920#q1',
    },
    {
        title: 'Chemistry Topic Question 2',
        courseName: 'Chemistry',
        courseId: 'CHEM-2920',
        classId: 'XII-Chem-4',
        dueDate: '',
        type: 'Short Answer',
        description: 'Describe the trends in atomic radius, ionization energy, and electronegativity across a period and down a group.',
        link: '/assignment/chemistry/CHEM-2920#q2',
    },
    {
        title: 'Chemistry Topic Question 3',
        courseName: 'Chemistry',
        courseId: 'CHEM-2920',
        classId: 'X-Chem-3',
        dueDate: '',
        type: 'Essay',
        description: "Explain Le Chatelier's Principle using industrial examples such as the Haber Process.",
        link: '/assignment/chemistry/CHEM-2920#q3',
    },
    {
        title: 'Physics Topic Question 1',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'XII-Phys-3',
        dueDate: '',
        type: 'Written Report',
        description: 'Using qton\u2019s Laws, explain the motion of a car on an inclined plane with and without friction.',
        link: '/assignment/physics/PHY-1205#q1',
    },
    {
        title: 'Physics Topic Question 2',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'XII-Phys-3',
        dueDate: '',
        type: 'Short Answer',
        description: 'Describe the energy transformations in a simple pendulum and derive the period formula.',
        link: '/assignment/physics/PHY-1205#q2',
    },
    {
        title: 'Physics Topic Question 3',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'XII-Phys-4',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Explain how lenses form images using ray diagrams, and distinguish between real and virtual images.',
        link: '/assignment/physics/PHY-1205#q3',
    },
    {
        title: 'Science Assignment Q1',
        courseName: 'Science',
        courseId: 'SCI-4321',
        classId: 'XII-Scie-1',
        dueDate: '',
        type: 'True/False',
        description: "Discuss how reqable and non-reqable resources affect the Earth's energy balance.",
        link: '/assignment/science/SCI-4321#q1',
    },
    {
        title: 'Science Assignment Q2',
        courseName: 'Science',
        courseId: 'SCI-4321',
        classId: 'XII-Scie-3',
        dueDate: '',
        type: 'Essay',
        description: 'Analyze the scientific basis for space colonization and the challenges of sustaining life beyond Earth.',
        link: '/assignment/science/SCI-4321#q2',
    },
    {
        title: 'Science Assignment Q3',
        courseName: 'Science',
        courseId: 'SCI-4321',
        classId: 'XII-Scie-4',
        dueDate: '',
        type: 'Fill in the Blank',
        description: "Describe the structure and role of the atmosphere in regulating Earth's temperature.",
        link: '/assignment/science/SCI-4321#q3',
    },
    {
        title: 'Biology Assignment Q4',
        courseName: 'Biology',
        courseId: 'BIO-2201',
        classId: 'XII-Biol-1',
        dueDate: '',
        type: 'Short Answer',
        description: 'Explain the structure and function of the human nervous system using real-world medical applications.',
        link: '/assignment/biology/BIO-2201#q4',
    },
    {
        title: 'Biology Assignment Q5',
        courseName: 'Biology',
        courseId: 'BIO-2201',
        classId: 'XI-Biol-1',
        dueDate: '',
        type: 'True/False',
        description: 'Describe genetic engineering and its impact on agriculture and medicine.',
        link: '/assignment/biology/BIO-2201#q5',
    },
    {
        title: 'Biology Assignment Q6',
        courseName: 'Biology',
        courseId: 'BIO-2201',
        classId: 'X-Biol-4',
        dueDate: '',
        type: 'Essay',
        description: 'Discuss the immune system\u2019s response to bacterial vs viral infections.',
        link: '/assignment/biology/BIO-2201#q6',
    },
    {
        title: 'Geography Assignment Q7',
        courseName: 'Geography',
        courseId: 'GEO-3010',
        classId: 'XII-Geog-4',
        dueDate: '',
        type: 'True/False',
        description: 'Explain how climate zones influence agricultural practices in different parts of the world.',
        link: '/assignment/geography/GEO-3010#q7',
    },
    {
        title: 'Geography Assignment Q8',
        courseName: 'Geography',
        courseId: 'GEO-3010',
        classId: 'XI-Geog-2',
        dueDate: '',
        type: 'True/False',
        description: 'Describe the economic and social impacts of rural-to-urban migration.',
        link: '/assignment/geography/GEO-3010#q8',
    },
    {
        title: 'Geography Assignment Q9',
        courseName: 'Geography',
        courseId: 'GEO-3010',
        classId: 'XI-Geog-2',
        dueDate: '',
        type: 'Written Report',
        description: 'Analyze the geographic factors contributing to natural disasters in Southeast Asia.',
        link: '/assignment/geography/GEO-3010#q9',
    },
    {
        title: 'Chemistry Assignment Q10',
        courseName: 'Chemistry',
        courseId: 'CHEM-1103',
        classId: 'XII-Chem-1',
        dueDate: '',
        type: 'True/False',
        description: 'Explain the principle of chromatography and its applications in forensic science.',
        link: '/assignment/chemistry/CHEM-1103#q10',
    },
    {
        title: 'Chemistry Assignment Q11',
        courseName: 'Chemistry',
        courseId: 'CHEM-1103',
        classId: 'XI-Chem-3',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Describe the process of titration and how it is used to determine concentration.',
        link: '/assignment/chemistry/CHEM-1103#q11',
    },
    {
        title: 'Chemistry Assignment Q12',
        courseName: 'Chemistry',
        courseId: 'CHEM-1103',
        classId: 'XII-Chem-3',
        dueDate: '',
        type: 'Short Answer',
        description: 'Discuss the chemical properties and uses of noble gases in modern industries.',
        link: '/assignment/chemistry/CHEM-1103#q12',
    },
    {
        title: 'Biology Assignment Q13',
        courseName: 'Biology',
        courseId: 'BIO-3302',
        classId: 'XI-Biol-3',
        dueDate: '',
        type: 'True/False',
        description: 'Explain the structure and function of the human nervous system using real-world medical applications.',
        link: '/assignment/biology/BIO-3302#q13',
    },
    {
        title: 'Biology Assignment Q14',
        courseName: 'Biology',
        courseId: 'BIO-3302',
        classId: 'X-Biol-2',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Describe genetic engineering and its impact on agriculture and medicine.',
        link: '/assignment/biology/BIO-3302#q14',
    },
    {
        title: 'Biology Assignment Q15',
        courseName: 'Biology',
        courseId: 'BIO-3302',
        classId: 'XI-Biol-3',
        dueDate: '',
        type: 'True/False',
        description: 'Discuss the immune system\u2019s response to bacterial vs viral infections.',
        link: '/assignment/biology/BIO-3302#q15',
    },
    {
        title: 'Physics Assignment Q16',
        courseName: 'Physics',
        courseId: 'PHY-2502',
        classId: 'X-Phys-4',
        dueDate: '',
        type: 'Short Answer',
        description: 'Explain the concept of wave-particle duality and its implications in quantum mechanics.',
        link: '/assignment/physics/PHY-2502#q16',
    },
    {
        title: 'Physics Assignment Q17',
        courseName: 'Physics',
        courseId: 'PHY-2502',
        classId: 'X-Phys-4',
        dueDate: '',
        type: 'Essay',
        description: 'Describe how transformers work and their role in power distribution.',
        link: '/assignment/physics/PHY-2502#q17',
    },
    {
        title: 'Physics Assignment Q18',
        courseName: 'Physics',
        courseId: 'PHY-2502',
        classId: 'X-Phys-2',
        dueDate: '',
        type: 'True/False',
        description: 'Analyze projectile motion and derive the equations for horizontal and vertical components.',
        link: '/assignment/physics/PHY-2502#q18',
    },
    {
        title: 'Physics Assignment Q19',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'X-Phys-3',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Explain the concept of wave-particle duality and its implications in quantum mechanics.',
        link: '/assignment/physics/PHY-1205#q19',
    },
    {
        title: 'Physics Assignment Q20',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'XI-Phys-3',
        dueDate: '',
        type: 'True/False',
        description: 'Describe how transformers work and their role in power distribution.',
        link: '/assignment/physics/PHY-1205#q20',
    },
    {
        title: 'Physics Assignment Q21',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'XI-Phys-2',
        dueDate: '',
        type: 'True/False',
        description: 'Analyze projectile motion and derive the equations for horizontal and vertical components.',
        link: '/assignment/physics/PHY-1205#q21',
    },
    {
        title: 'Geography Assignment Q22',
        courseName: 'Geography',
        courseId: 'GEO-2222',
        classId: 'X-Geog-2',
        dueDate: '',
        type: 'Short Answer',
        description: 'Explain how climate zones influence agricultural practices in different parts of the world.',
        link: '/assignment/geography/GEO-2222#q22',
    },
    {
        title: 'Geography Assignment Q23',
        courseName: 'Geography',
        courseId: 'GEO-2222',
        classId: 'XII-Geog-2',
        dueDate: '',
        type: 'Essay',
        description: 'Describe the economic and social impacts of rural-to-urban migration.',
        link: '/assignment/geography/GEO-2222#q23',
    },
    {
        title: 'Geography Assignment Q24',
        courseName: 'Geography',
        courseId: 'GEO-2222',
        classId: 'X-Geog-2',
        dueDate: '',
        type: 'Short Answer',
        description: 'Analyze the geographic factors contributing to natural disasters in Southeast Asia.',
        link: '/assignment/geography/GEO-2222#q24',
    },
    {
        title: 'Science Assignment Q25',
        courseName: 'Science',
        courseId: 'SCI-5533',
        classId: 'XII-Scie-4',
        dueDate: '',
        type: 'Written Report',
        description: "Discuss how reqable and non-reqable resources affect the Earth's energy balance.",
        link: '/assignment/science/SCI-5533#q25',
    },
    {
        title: 'Science Assignment Q26',
        courseName: 'Science',
        courseId: 'SCI-5533',
        classId: 'XI-Scie-3',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Analyze the scientific basis for space colonization and the challenges of sustaining life beyond Earth.',
        link: '/assignment/science/SCI-5533#q26',
    },
    {
        title: 'Science Assignment Q27',
        courseName: 'Science',
        courseId: 'SCI-5533',
        classId: 'X-Scie-3',
        dueDate: '',
        type: 'Written Report',
        description: "Describe the structure and role of the atmosphere in regulating Earth's temperature.",
        link: '/assignment/science/SCI-5533#q27',
    },
    {
        title: 'Chemistry Assignment Q28',
        courseName: 'Chemistry',
        courseId: 'CHEM-1211',
        classId: 'XII-Chem-1',
        dueDate: '',
        type: 'Written Report',
        description: 'Explain the principle of chromatography and its applications in forensic science.',
        link: '/assignment/chemistry/CHEM-1211#q28',
    },
    {
        title: 'Chemistry Assignment Q29',
        courseName: 'Chemistry',
        courseId: 'CHEM-1211',
        classId: 'XII-Chem-1',
        dueDate: '',
        type: 'Short Answer',
        description: 'Describe the process of titration and how it is used to determine concentration.',
        link: '/assignment/chemistry/CHEM-1211#q29',
    },
    {
        title: 'Chemistry Assignment Q30',
        courseName: 'Chemistry',
        courseId: 'CHEM-1211',
        classId: 'XII-Chem-2',
        dueDate: '',
        type: 'True/False',
        description: 'Discuss the chemical properties and uses of noble gases in modern industries.',
        link: '/assignment/chemistry/CHEM-1211#q30',
    },
    {
        title: 'Biology Assignment Q31',
        courseName: 'Biology',
        courseId: 'BIO-4120',
        classId: 'XI-Biol-2',
        dueDate: '',
        type: 'Written Report',
        description: 'Explain the structure and function of the human nervous system using real-world medical applications.',
        link: '/assignment/biology/BIO-4120#q31',
    },
    {
        title: 'Biology Assignment Q32',
        courseName: 'Biology',
        courseId: 'BIO-4120',
        classId: 'XI-Biol-4',
        dueDate: '',
        type: 'Short Answer',
        description: 'Describe genetic engineering and its impact on agriculture and medicine.',
        link: '/assignment/biology/BIO-4120#q32',
    },
    {
        title: 'Biology Assignment Q33',
        courseName: 'Biology',
        courseId: 'BIO-4120',
        classId: 'X-Biol-1',
        dueDate: '',
        type: 'Written Report',
        description: 'Discuss the immune system\u2019s response to bacterial vs viral infections.',
        link: '/assignment/biology/BIO-4120#q33',
    },
    {
        title: 'Science Assignment Q34',
        courseName: 'Science',
        courseId: 'SCI-2098',
        classId: 'XI-Scie-3',
        dueDate: '',
        type: 'Fill in the Blank',
        description: "Discuss how reqable and non-reqable resources affect the Earth's energy balance.",
        link: '/assignment/science/SCI-2098#q34',
    },
    {
        title: 'Science Assignment Q35',
        courseName: 'Science',
        courseId: 'SCI-2098',
        classId: 'XII-Scie-1',
        dueDate: '',
        type: 'Written Report',
        description: 'Analyze the scientific basis for space colonization and the challenges of sustaining life beyond Earth.',
        link: '/assignment/science/SCI-2098#q35',
    },
    {
        title: 'Science Assignment Q36',
        courseName: 'Science',
        courseId: 'SCI-2098',
        classId: 'XII-Scie-1',
        dueDate: '',
        type: 'True/False',
        description: "Describe the structure and role of the atmosphere in regulating Earth's temperature.",
        link: '/assignment/science/SCI-2098#q36',
    },
    {
        title: 'Biology Assignment Q37',
        courseName: 'Biology',
        courseId: 'BIO-1015',
        classId: 'X-Biol-2',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Explain the structure and function of the human nervous system using real-world medical applications.',
        link: '/assignment/biology/BIO-1015#q37',
    },
    {
        title: 'Biology Assignment Q38',
        courseName: 'Biology',
        courseId: 'BIO-1015',
        classId: 'X-Biol-1',
        dueDate: '',
        type: 'True/False',
        description: 'Describe genetic engineering and its impact on agriculture and medicine.',
        link: '/assignment/biology/BIO-1015#q38',
    },
    {
        title: 'Biology Assignment Q39',
        courseName: 'Biology',
        courseId: 'BIO-1015',
        classId: 'X-Biol-4',
        dueDate: '',
        type: 'Fill in the Blank',
        description: 'Discuss the immune system\u2019s response to bacterial vs viral infections.',
        link: '/assignment/biology/BIO-1015#q39',
    },
    {
        title: 'Geography Assignment Q40',
        courseName: 'Geography',
        courseId: 'GEO-8787',
        classId: 'X-Geog-1',
        dueDate: '',
        type: 'Short Answer',
        description: 'Explain how climate zones influence agricultural practices in different parts of the world.',
        link: '/assignment/geography/GEO-8787#q40',
    },
    {
        title: 'Geography Assignment Q41',
        courseName: 'Geography',
        courseId: 'GEO-8787',
        classId: 'XI-Geog-3',
        dueDate: '',
        type: 'Written Report',
        description: 'Describe the economic and social impacts of rural-to-urban migration.',
        link: '/assignment/geography/GEO-8787#q41',
    },
    {
        title: 'Geography Assignment Q42',
        courseName: 'Geography',
        courseId: 'GEO-8787',
        classId: 'X-Geog-2',
        dueDate: '',
        type: 'True/False',
        description: 'Analyze the geographic factors contributing to natural disasters in Southeast Asia.',
        link: '/assignment/geography/GEO-8787#q42',
    },
    {
        title: 'Chemistry Assignment Q43',
        courseName: 'Chemistry',
        courseId: 'CHEM-2920',
        classId: 'XII-Chem-2',
        dueDate: '',
        type: 'True/False',
        description: 'Explain the principle of chromatography and its applications in forensic science.',
        link: '/assignment/chemistry/CHEM-2920#q43',
    },
    {
        title: 'Chemistry Assignment Q44',
        courseName: 'Chemistry',
        courseId: 'CHEM-2920',
        classId: 'XII-Chem-4',
        dueDate: '',
        type: 'Written Report',
        description: 'Describe the process of titration and how it is used to determine concentration.',
        link: '/assignment/chemistry/CHEM-2920#q44',
    },
    {
        title: 'Chemistry Assignment Q45',
        courseName: 'Chemistry',
        courseId: 'CHEM-2920',
        classId: 'X-Chem-2',
        dueDate: '',
        type: 'Short Answer',
        description: 'Discuss the chemical properties and uses of noble gases in modern industries.',
        link: '/assignment/chemistry/CHEM-2920#q45',
    },
    {
        title: 'Physics Assignment Q46',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'X-Phys-3',
        dueDate: '',
        type: 'Written Report',
        description: 'Explain the concept of wave-particle duality and its implications in quantum mechanics.',
        link: '/assignment/physics/PHY-1205#q46',
    },
    {
        title: 'Physics Assignment Q47',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'XII-Phys-1',
        dueDate: '',
        type: 'True/False',
        description: 'Describe how transformers work and their role in power distribution.',
        link: '/assignment/physics/PHY-1205#q47',
    },
    {
        title: 'Physics Assignment Q48',
        courseName: 'Physics',
        courseId: 'PHY-1205',
        classId: 'X-Phys-3',
        dueDate: '',
        type: 'True/False',
        description: 'Analyze projectile motion and derive the equations for horizontal and vertical components.',
        link: '/assignment/physics/PHY-1205#q48',
    },
];
